services:
  devdb:
    image: docker.io/postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "devdb_data:/var/lib/postgresql/data"

  devcms:
    build: ..
    user: "0:0"
    depends_on:
      - "devdb"
    environment:
      CMS_CONFIG: /home/cmsuser/cms/etc/cms-devdb.toml
    volumes:
      - "..:/home/cmsuser/src"
      - ../config-data:/home/cmsuser/cms/etc
      
    privileged: true
    cgroup: host
    command: >
      bash -c "
        cp -Rf /home/cmsuser/src/config-data/. /home/cmsuser/cms/etc/
        cp /home/cmsuser/src/config-data/nginx/nginx.conf /etc/nginx/nginx.conf
        cat /home/cmsuser/src/config-data/nginx/sites-available/cms.conf > /etc/nginx/sites-available/default
        cp -Rf /home/cmsuser/src/config-data/html/. /var/www/html/

        tail -f /dev/null
      "
    ports:
      - 8888:80

volumes:
  devdb_data:
