server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        root /var/www/html;
        index index.html;
    }

    location /m1-t1-work/ {
        proxy_pass http://127.0.0.1:9501/; 
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /m1-t1-mid/ {
        proxy_pass http://127.0.0.1:9502/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    location /m1-t1-final/ {
        proxy_pass http://127.0.0.1:9503/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /m1-t2-work/ {
        proxy_pass http://127.0.0.1:9504/; 
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /m1-t2-mid/ {
        proxy_pass http://127.0.0.1:9505/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    location /m1-t2-final/ {
        proxy_pass http://127.0.0.1:9506/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /m2-t1-work/ {
        proxy_pass http://127.0.0.1:9507/; 
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /m2-t1-mid/ {
        proxy_pass http://127.0.0.1:9508/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    location /m2-t1-final/ {
        proxy_pass http://127.0.0.1:9509/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /teacher-only/ {
        proxy_pass http://127.0.0.1:9510/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
    
    location /admin/ {
        proxy_pass http://127.0.0.1:8889/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
